name: Test & Deploy

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - run: npm test

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04

    needs:
      - test

    if: ${{ github.event_name == 'push' }}

    steps:
      - run: echo "Coming soon"
